#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'docker-compose==1.6.2','console_scripts','docker-compose'
__requires__ = 'docker-compose==1.6.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('docker-compose==1.6.2', 'console_scripts', 'docker-compose')()
    )
